server:
  port: 80

spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning?servierTimezone=UTC
    username: root
    password:
logging:
  level:
    com.myafaslove: debug
